kind: Service
apiVersion: v1
metadata:
  name: webserver-svc
spec:
  selector:
    app: webserver
  type: NodePort
  ports:
    - name: webserver-port
      port: 9090
      targetPort: 9090
      nodePort: 30000
